image: maven:3.8.2-openjdk-17

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn clean install
          - mvn clean -Preports jacoco:prepare-agent install jacoco:report coveralls:report -DrepoToken=${COVERALLS_TOKEN}
          - bash <(curl -s https://codecov.io/bash)
          - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find **/jacoco*.xml -printf '-r %p ')
