name: KHC Build, Test, Coverage and Report

on:
  push:
    branches: [ main ]
  pull_request_target:
    types:
      - closed

jobs:
  build-test-coverage-report:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v5
        - name: Set up JDK 21
          uses: actions/setup-java@v5
          with:
            java-version: '21'
            distribution: 'adopt'

        - name: Build and Test MAVEN for Reactive
          run:  make no-test

        - name: Build and Test MAVEN for Reports
          run:  make coverage

        - name: Coverage Reports
          run: mvn omni-coveragereporter:report
          env:
             COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
             CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
             CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
